name: CI
on: [pull_request]
env:
  node-version: 16
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node-version }}"
          cache: npm
      - name: Install Node.js dependencies
        run: |
          npm ci
      - name: Run lint
        run: |
          npm run lint
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node-version }}"
          cache: npm
      - name: Install Node.js dependencies
        run: |
          npm ci
      - name: Run test
        run: |
          npm run test
      - name: Run package
        run: |
          npm run package
      - name: Run action
        uses: ./
